### ISSUE TITLE
Flash Events - Read From AWS

### ISSUE THREAD

**Issue by markKHA** [KimleyHorn/SigOpsMetrics#330]
Create a new file in the SigOpsMetricsCalcEngine project to gather Flash Events. The raw data is saved in Parquet files on AWS. We need to find the flash events, calculate how long they lasted, and save them in a new MySQL table.

See Mark and Carter for more details.

**Comment by carterliukimleyhorn** [comment]
Add table raw_event_log
Timestamp: Datetime
SignalID: int
EventCode: int
EventParam: int
DeviceID: int
index_level: int
